// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Telumera.Services.Analytics.Api;

#nullable disable

namespace Telumera.Services.Analytics.Api.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260902103433_AddAggregationCheckpoint")]
    partial class AddAggregationCheckpoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Telumera.Idempotency.ProcessedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_processed_events");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("Telumera.Services.Analytics.Api.AggregationCheckpoint", b =>
                {
                    b.Property<string>("JobName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_name");

                    b.Property<DateTimeOffset>("Watermark")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("watermark");

                    b.HasKey("JobName")
                        .HasName("pk_aggregation_checkpoints");

                    b.ToTable("aggregation_checkpoints", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
